# -*- coding: utf-8 -*-
"""흉부 X-레이 코로나 진단 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WM6FpJfYYuuVoAeOvVBec1T2wDy5TaEI
"""

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

"""##Load library

"""

from glob import glob
import cv2
from matplotlib import pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from keras.applications.densenet import DenseNet169
from sklearn.model_selection import cross_validate, KFold
from keras.losses import SparseCategoricalCrossentropy, CategoricalCrossentropy
from xgboost import XGBClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, roc_curve, auc

# from google.colab import drive

"""##Import Data

"""

drive.mount('/content/drive')
! wget -P /content/drive/MyDrive https://github.com/muhammedtalo/COVID-19/archive/refs/heads/master.zip
! unzip -q /content/drive/MyDrive/master.zip -d /content/drive/MyDrive/Dataset

"""##Drive access"""

drive.mount('/content/drive')

"""##Data access"""

images_path = {}
images_path["Covid"] = glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/Covid-19/*.png")
images_path["Covid"] += glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/Covid-19/*.jpeg")
images_path["Covid"] += glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/Covid-19/*.jpg")

images_path["NoFindings"] = glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/No_findings/*.png")
images_path["NoFindings"] += glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/No_findings/*.jpeg")
images_path["NoFindings"] += glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/No_findings/*.jpg")

images_path["Pneumonia"] = glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/Pneumonia/*.png")
images_path["Pneumonia"] += glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/Pneumonia/*.jpeg")
images_path["Pneumonia"] += glob("/content/drive/MyDrive/Dataset/COVID-19-master/X-Ray Image DataSet/Pneumonia/*.jpg")

print(images_path["Covid"])
print()
print(images_path["NoFindings"])
print()
print(images_path["Pneumonia"])

images_class = {
    "Covid": 0,
    "Pneumonia": 1,
    "NoFindings": 2 
}

"""##Number of Data"""

print(len(images_path['Covid']))
print(len(images_path['NoFindings']))
print(len(images_path['Pneumonia']))

"""##Data output"""

""
X = []
Y = []

for label in images_path:
    for image_path in images_path[label]:
        image = cv2.imread(image_path)
        image = cv2.resize(image,(224, 224))
        X.append(image)
        Y.append(images_class[label])

plt.imshow(X[0])
plt.show()

print(np.array(X).shape)
print(np.array(Y).shape)

plt.imshow(X[1124])

"""##Create a Model







"""

x = np.array(X)
y = np.array(Y)

# initial pre trained model
pre_trained_models = {}
pre_trained_models["DenseNet169"] = DenseNet169(include_top=False, input_shape=(224, 224, 3), pooling="avg")

features = pre_trained_models["DenseNet169"].predict(x)

"""##train, test split Data"""

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=80)

X_train = pre_trained_models["DenseNet169"].predict(X_train)
X_test = pre_trained_models["DenseNet169"].predict(X_test)

"""##Classification"""

XGB_Classifier = XGBClassifier(learning_rate=0.44, n_estimators=100, random_state=0, seed=0, gamma=0)

#Model train 
XGB_Classifier.fit(X_train, Y_train)


#test data predict
Y_pred = XGB_Classifier.predict(X_test)
Y_pred

"""##Model Verification"""

result = {}


result["Accuracy score"] = accuracy_score(Y_test, Y_pred)
result["confusion matrix"] = confusion_matrix(Y_test, Y_pred)
result["f1 score"] = f1_score(Y_test, Y_pred, average="macro")
result["precision score"] = precision_score(Y_test, Y_pred, average="macro")
result["Sensitivity"] = result["confusion matrix"][0,0] / (result["confusion matrix"][0,0] + result["confusion matrix"][0,1])
result["Specifity"] = result["confusion matrix"][1,1] / (result["confusion matrix"][1,0] + result["confusion matrix"][1,1])

print(f"\nAccuracy score : ", result["Accuracy score"])
print(f"\nconfusion matrix : \n", result["confusion matrix"])
print(f"\nf1 score : ", result["f1 score"])
print(f"\nprecision score : ", result["precision score"])
print(f"\nSpecifity : ", result["Specifity"])
print(f"\nSensitivity : ", result["Sensitivity"])

"""##model evaluation"""

from sklearn.metrics import roc_curve, auc

from sklearn import preprocessing
y_test = preprocessing.label_binarize(Y_test, classes=[0, 1])
y_pred = preprocessing.label_binarize(Y_pred, classes=[0, 1])
print(y_test.shape)
print(y_pred.shape)

n_classes = list(Y_test.shape)

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(2):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area

fpr["micro"], tpr["micro"], _ = roc_curve(y_test.ravel(), y_pred.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

plt.figure()
lw = 2
plt.plot(fpr[1], tpr[1], color='darkorange',
         lw=lw, label='ROC curve (AUC = %0.2f)' % roc_auc[1])
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.0])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")
plt.savefig("roc.svg", format="svg")
plt.show()

import sklearn
import pandas as pd

scoring = ['precision_macro', 'f1_macro', "accuracy"]

rs = 229
cv = KFold(n_splits=5, random_state=rs, shuffle=True)
scores = cross_validate(XGB_Classifier,features, y, cv=cv, scoring=scoring)
scr = pd.DataFrame(scores)
print(f"======== KFold random state {rs} ==========")
print(scr)
print("accuracy avg : ", scr["test_accuracy"].mean())

"""##Classification model performance metrics"""

f = 0
for train_ix, test_ix in cv.split(features):
    # get data
    train_X, test_X = features[train_ix], features[test_ix]
    train_y, test_y = y[train_ix], y[test_ix]
    # fit model
    model = XGB_Classifier
    model.fit(train_X, train_y)
    # evaluate model
    yhat = model.predict(test_X)
    acc = accuracy_score(test_y, yhat)
    # store score
    print(f"\n confusion matrix fold {f}")
    f = f+1
    print(confusion_matrix(test_y, yhat))